[env]
# read/write to/from files relative to the workspace even when running in this
# directory
CARGO_WORKSPACE_DIR = { value = "", relative = true }

[env]
# If we're running in the project workspace, then we should set the workspace env var so we read/write to/from files relative to the workspace.
CARGO_WORKSPACE_DIR = { value = "", relative = true }
